language: R
cache: packages

matrix:
    include:
        - os: linux
          r: oldrel
        - os: linux
          r: release
        - os: linux
          r: devel
        - os: osx
          r: oldrel
        - os: osx
          r: release
